// Next Components
import Head from 'next/head';
import Link from 'next/link';

// Styled Components
import styled from 'styled-components';

// Types
import type { NextPage } from 'next';

const Test = styled.div`
  background-color: blue;
  color: white;
  height: 100px;
`;

const Home: NextPage = () => {
  return (
    <Test>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Link href='/login'>
          <a>Login</a>
        </Link>

        <Link href='/editor'>
          <a>Editor</a>
        </Link>
      </main>

      <footer>
        
      </footer>
    </Test>
  )
}

export default Home
